api:
  mainUrl: http://localhost:8080/
  endpoints:
    profile:
      url: profile/
    nearby:
      url: location/dist/
    newLocation:
      url: location/new/
    deleteProfile:
      url: profile/delete

inputs:
  comparison: &comparisonOperator
    name: is
    type: select
    value: lt
    options:
      lt:
        value: lt
        display: less than
        javaClass: JSONLess
      leq:
        value: leq
        display: less than or equal to
        javaClass: JSONLessEqual
      eq:
        value: eq
        display: equal to
        javaClass: JSONEqual
      geq:
        value: geq
        display: greater than or equal to
        javaClass: JSONGreaterEqual
      gt:
        value: gt
        display: greater than
        javaClass: JSONGreater

profile:
  properties:
    temperature:
      name: temperature
      inputs:
        is: *comparisonOperator
        than:
          name: than
          displayName: false
          type: range
          valueType: int
          iconBefore: ion-ios-snowy
          iconAfter: ion-ios-sunny-outline
          min: -40
          max: 60
          value: 20
      javaStructure:
        type: attributeToObject
        classFrom: is
        valueFrom: than
    humidity:
      name: humidity
      inputs:
        is: *comparisonOperator
        than:
          name: than
          displayName: false
          type: range
          valueType: int
          iconBefore: ion-ios-sunny-outline
          iconAfter: ion-ios-rainy-outline
          min: 0
          max: 100
          value: 50
      javaStructure:
        type: attributeToObject
        classFrom: is
        valueFrom: than
